apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api
          image: acrformymicroservices-test.azurecr.io/todos-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: TODO_API_PORT
              value: "8082"
            - name: JWT_SECRET
              value: "PRFT"
            - name: REDIS_HOST
              value: "microservices-redis.redis.cache.windows.net"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: microservices
spec:
  selector:
    app: todos-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
