apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: acrformymicroservices.azurecr.io/auth-api:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_API_PORT
              value: "8000"
            - name: USERS_API_ADDRESS
              value: "http://users-api:8083"
            - name: JWT_SECRET
              value: "PRFT"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: microservices
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
