name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - master
      - infra/dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                                 --name ${{ secrets.AKS_CLUSTER_NAME }} \
                                 --overwrite-existing

      - name: Azure Container Registry Login
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Get Redis Primary Key
        id: redis-key
        run: |
          REDIS_KEY=$(az redis list-keys --name microservices-redis --resource-group microservices-rg --query "primaryKey" -o tsv)
          echo "::add-mask::$REDIS_KEY"
          echo "REDIS_PASSWORD=$REDIS_KEY" >> $GITHUB_ENV

      - name: Create Redis Secret
        run: |
          kubectl create secret generic redis-secret \
            --namespace microservices \
            --from-literal=REDIS_PASSWORD="$REDIS_PASSWORD" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Build and push Docker images
        run: |
          for dir in ./auth-api ./frontend ./users-api ./todos-api ./log-message-processor; do
            name=$(basename $dir)
            docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$name:${{ env.IMAGE_TAG }} $dir
            docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$name:${{ env.IMAGE_TAG }}
          done

      - name: Replace image tag in manifests
        run: |
          for dir in ./auth-api ./frontend ./users-api ./todos-api ./log-message-processor; do
            sed -i "s|image: .*:.*|image: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$(basename $dir):${{ env.IMAGE_TAG }}|" $dir/${dir##*/}-deployment.yml
          done

      - name: Apply Kubernetes manifests
        run: |
          for dir in ./auth-api ./frontend ./users-api ./todos-api ./log-message-processor; do
            kubectl apply -f $dir/${dir##*/}-deployment.yml --namespace microservices
          done

      - name: Rollout restart (optional refuerzo)
        run: |
          for app in auth-api frontend users-api todos-api log-message-processor; do
            kubectl rollout restart deployment $app --namespace microservices
          done
